---

- name: merge ansible configuration between defaults and custom
  ansible.builtin.set_fact:
    ansible_config: "{{ ansible_defaults_config | combine(ansible_config, recursive=True) }}"

- name: create ansible configuration
  ansible.builtin.template:
    src: ansible.cfg.j2
    dest: /etc/ansible.cfg
    owner: root
    group: root
    mode: 0644
    backup: true

...
